[tool.black]
line-length = 120

[tool.isort]
profile="black"
combine_as_imports = true
combine_star = true
line_length = 120

[tool.pyright]
include = [
    "WorstBot"
]
exclude = [
    "**/__pycache__",
    "logs"
]
reportMissingImports = "none"
reportUnnecessaryTypeIgnoreComment = "warning"
pythonVersion="3.12"
typeCheckingMode = "basic"
venv = "venv"
venvPath = "."
pythonPlatform = "Linux"